### ISSUE TITLE
About dependencies versions

### ISSUE THREAD

**Issue by AyberkAhmet** [Enough-Software/enough_mail_icalendar#1]
Will dependencies versions be upgraded?

>   enough_mail: ^2.1.1
  enough_mail_icalendar: ^0.2.0
  enough_icalendar: ^0.13.0

> Running "flutter pub get" in calendar_event...
Resolving dependencies...
Because every version of enough_mail_icalendar depends on enough_mail ^1.3.6 and calendar_event depends on enough_mail ^2.1.1, enough_mail_icalendar is forbidden.
So, because calendar_event depends on enough_mail_icalendar ^0.2.0, version solving failed.
pub get failed

---------------------------------------------------------------------------------------------------------------

>   enough_mail: any
  enough_mail_icalendar: ^0.2.0
  enough_icalendar: any

> Running "flutter pub get" in calendar_event...
Resolving dependencies...
Because every version of enough_mail_icalendar depends on enough_mail ^1.3.6 which depends on xml ^5.1.2, every version of enough_mail_icalendar requires xml ^5.1.2.
And because docx_template >=0.3.3 depends on xml ^6.1.0, enough_mail_icalendar is incompatible with docx_template >=0.3.3.
So, because calendar_event depends on both docx_template ^0.3.3 and enough_mail_icalendar ^0.2.0, version solving failed.
pub get failed

**Comment by robert-virkus** [comment]
Thanks a lot, I uploaded the new release v0.2.1 with updated dependencies

**Comment by robert-virkus** [comment]
You can also use `dependency_overrides` to force `xml: ^6.1.0`, by the way

**Comment by AyberkAhmet** [comment]
Thank you :)
